package plan

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/beeradb/truss/internal/gates"
)

// --- Declarations -----------------------------------------------------
//
// Every case below is generated by the REAL tofu binary, never a
// hand-written plan-JSON fixture: docs/work-items.md's own standard for
// this codebase is to verify a `tofu show -json` shape against the real
// thing before depending on it, and that is exactly what was missing when
// this gate was deferred twice. terraform_data is a builtin resource type --
// `tofu init` reports it as built in to OpenTofu rather than resolving a
// provider for it -- so these fixtures need no provider download and no
// network. (The builtin's fully qualified name is not written here: it is a
// host-and-path shape, and scripts/leakscan refuses those wherever they
// appear rather than trying to tell a vendor's constant from a deployment's
// address.)
//
// ⚠️ If tofu is not on PATH, these tests FAIL rather than skip. A check
// that did not run is not a check that passed -- the whole reason this gate
// was deferred twice was "no tofu binary here" going unverified rather than
// unrun.

// requireTofu resolves the real tofu binary or fails the test outright.
func requireTofu(t *testing.T) string {
	t.Helper()
	bin, err := exec.LookPath("tofu")
	if err != nil {
		t.Fatalf("tofu is required for TestDeclarations* and was not found on PATH (%v); this test must fail, not skip, when it cannot run", err)
	}
	return bin
}

// runTofu runs one tofu subcommand in dir and returns its stdout, failing
// the test with both streams on any error.
func runTofu(t *testing.T, tofuBin, dir string, args ...string) []byte {
	t.Helper()
	cmd := exec.Command(tofuBin, args...)
	cmd.Dir = dir
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("tofu %s: %v\n--- stdout ---\n%s\n--- stderr ---\n%s",
			strings.Join(args, " "), err, stdout.String(), stderr.String())
	}
	return stdout.Bytes()
}

// planJSONFor writes files (path relative to a fresh root -> content) under
// t.TempDir(), plans them for real, and returns `tofu show -json`'s output.
func planJSONFor(t *testing.T, tofuBin string, files map[string]string) []byte {
	t.Helper()
	dir := t.TempDir()
	for rel, content := range files {
		full := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir for %s: %v", rel, err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", rel, err)
		}
	}

	runTofu(t, tofuBin, dir, "init", "-input=false")
	runTofu(t, tofuBin, dir, "plan", "-out=plan.tfplan", "-input=false")
	return runTofu(t, tofuBin, dir, "show", "-json", "plan.tfplan")
}

func findDeclaration(t *testing.T, decls []gates.Declaration, address string) gates.Declaration {
	t.Helper()
	for _, d := range decls {
		if d.Address == address {
			return d
		}
	}
	t.Fatalf("no declaration for address %q among %d declarations: %+v", address, len(decls), decls)
	return gates.Declaration{}
}

// TestDeclarationsFindsARootProvisioner: a provisioner on a resource
// declared directly in the root module appears at
// configuration.root_module.resources[].provisioners[].type, and a
// resource with no provisioner block carries no "provisioners" key at all
// -- confirmed against tofu 1.12.6, and asserted both ways here so a
// regression that starts reporting every resource as provisioned would
// also be caught.
func TestDeclarationsFindsARootProvisioner(t *testing.T) {
	tofuBin := requireTofu(t)
	planJSON := planJSONFor(t, tofuBin, map[string]string{
		"main.tf": `
resource "terraform_data" "root_clean" {
  input = "clean"
}

resource "terraform_data" "root_prov" {
  input = "root"
  provisioner "local-exec" {
    command = "echo root"
  }
}
`,
	})

	decls, err := Declarations(planJSON)
	if err != nil {
		t.Fatalf("Declarations: %v", err)
	}

	prov := findDeclaration(t, decls, "terraform_data.root_prov")
	if got := prov.Provisioners; len(got) != 1 || got[0] != "local-exec" {
		t.Errorf("terraform_data.root_prov: want [local-exec], got %v", got)
	}
	if prov.Type != "terraform_data" {
		t.Errorf("terraform_data.root_prov: want type terraform_data, got %q", prov.Type)
	}

	clean := findDeclaration(t, decls, "terraform_data.root_clean")
	if len(clean.Provisioners) != 0 {
		t.Errorf("terraform_data.root_clean: want no provisioners, got %v", clean.Provisioners)
	}
}

// TestDeclarationsFindsAProvisionerOneModuleDeep: a provisioner inside a
// child module does NOT appear under root_module.resources -- that array is
// empty for it -- it appears under
// root_module.module_calls.<name>.module.resources[]. A gate reading only
// the root module would report zero declarations for this fixture; this
// test is what "watch it fail" (see the task notes) breaks first.
func TestDeclarationsFindsAProvisionerOneModuleDeep(t *testing.T) {
	tofuBin := requireTofu(t)
	planJSON := planJSONFor(t, tofuBin, map[string]string{
		"main.tf": `
module "m" {
  source = "./modA"
}
`,
		"modA/main.tf": `
resource "terraform_data" "inner" {
  input = "innerA"
  provisioner "local-exec" {
    command = "echo innerA"
  }
}
`,
	})

	decls, err := Declarations(planJSON)
	if err != nil {
		t.Fatalf("Declarations: %v", err)
	}

	inner := findDeclaration(t, decls, "module.m.terraform_data.inner")
	if got := inner.Provisioners; len(got) != 1 || got[0] != "local-exec" {
		t.Errorf("module.m.terraform_data.inner: want [local-exec], got %v", got)
	}
}

// TestDeclarationsFindsAProvisionerTwoModulesDeep: the recursion into
// module_calls[*].module must not stop at one level. The platform this
// serves is almost entirely modules calling modules, so this is the
// difference between a working gate and a decorative one.
func TestDeclarationsFindsAProvisionerTwoModulesDeep(t *testing.T) {
	tofuBin := requireTofu(t)
	planJSON := planJSONFor(t, tofuBin, map[string]string{
		"main.tf": `
module "m" {
  source = "./modA"
}
`,
		"modA/main.tf": `
module "n" {
  source = "./modB"
}
`,
		"modA/modB/main.tf": `
resource "terraform_data" "deep" {
  input = "deepB"
  provisioner "local-exec" {
    command = "echo deepB"
  }
}
`,
	})

	decls, err := Declarations(planJSON)
	if err != nil {
		t.Fatalf("Declarations: %v", err)
	}

	deep := findDeclaration(t, decls, "module.m.module.n.terraform_data.deep")
	if got := deep.Provisioners; len(got) != 1 || got[0] != "local-exec" {
		t.Errorf("module.m.module.n.terraform_data.deep: want [local-exec], got %v", got)
	}
}

// TestDeclarationsFindsNoneInACleanConfig: a config with resources at the
// root and nested two modules deep, none of them carrying a provisioner,
// must report every resource found but with an empty Provisioners slice for
// each -- proving the clean path is not "found nothing" by accident of a
// broken walk, but "found these, and none of them have one".
func TestDeclarationsFindsNoneInACleanConfig(t *testing.T) {
	tofuBin := requireTofu(t)
	planJSON := planJSONFor(t, tofuBin, map[string]string{
		"main.tf": `
resource "terraform_data" "root_clean" {
  input = "clean"
}

module "m" {
  source = "./modA"
}
`,
		"modA/main.tf": `
resource "terraform_data" "inner_clean" {
  input = "inner"
}

module "n" {
  source = "./modB"
}
`,
		"modA/modB/main.tf": `
resource "terraform_data" "deep_clean" {
  input = "deep"
}
`,
	})

	decls, err := Declarations(planJSON)
	if err != nil {
		t.Fatalf("Declarations: %v", err)
	}
	if len(decls) != 3 {
		t.Fatalf("want 3 declarations, got %d: %+v", len(decls), decls)
	}
	for _, addr := range []string{
		"terraform_data.root_clean",
		"module.m.terraform_data.inner_clean",
		"module.m.module.n.terraform_data.deep_clean",
	} {
		d := findDeclaration(t, decls, addr)
		if len(d.Provisioners) != 0 {
			t.Errorf("%s: want no provisioners, got %v", addr, d.Provisioners)
		}
	}
}

// TestDeclarationsRefusesGarbage: a payload that is not a `tofu show -json`
// plan is an error, never an empty slice -- an empty slice reads as
// "nothing declared", which is a gate passing on garbage rather than
// refusing to judge it.
func TestDeclarationsRefusesGarbage(t *testing.T) {
	cases := []struct {
		name string
		body []byte
	}{
		{"not json at all", []byte("this is not json")},
		{"valid json with no configuration key", []byte(`{"format_version": "1.2"}`)},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			decls, err := Declarations(c.body)
			if err == nil {
				t.Fatalf("want an error, got %d declarations: %+v", len(decls), decls)
			}
		})
	}
}
