package ansible

import (
	"fmt"
	"net"
	"sort"
	"strings"
)

// Target is one machine a play will be run against: truss's own name for
// it, and everything ansible needs in order to reach it.
//
// ⚠️ THE NAME AND THE ADDRESS ARE SEPARATE FIELDS AND THAT IS THE WHOLE
// POINT OF THIS TYPE. ansible-playbook accepts an inline host list --
// `-i "probe.invalid:22,"` -- and it parses the port, so the temptation is to
// skip the file entirely. Measured against ansible 2.16.3, that form names
// the host BY ITS ADDRESS: inventory_hostname becomes "probe.invalid", --limit
// stops matching the name the inventory record uses, and a play can no
// longer say which machine it is on. The other inline form,
// `-i "dev-agent," -e ansible_host=...`, keeps the name and is worse: -e is
// GLOBAL, so with two hosts both receive the same address. Measured, again
// at 2.16.3: "alpha -> probe.invalid" and "dev-agent -> probe.invalid". Correct at one
// host and silently wrong at two is the shape this project has been bitten
// by repeatedly, so the inventory is a real file with per-host variables.
type Target struct {
	// Name is the machine's inventory record name, and becomes its
	// ansible inventory_hostname. Required.
	Name string
	// Address is where to reach it, as "<host>" or "<host>:<port>".
	//
	// ⚠️ EMPTY IS MEANINGFUL AND IS NOT AN ERROR: it means the name IS the
	// address, which is exactly the case for a machine reached over a
	// tailnet, where MagicDNS resolves the record's own name. The renderer
	// then writes no ansible_host at all and ansible connects to
	// inventory_hostname, rather than this package inventing a resolution
	// path -- fully-qualifying against a tailnet domain would be this
	// deployment's DNS compiled into the engine.
	Address string
	// User is the login account, or empty for unstated. Unstated writes no
	// ansible_user, so a play's own remote_user still decides.
	User string
	// Groups are the ansible groups this machine belongs to, derived from
	// facts its inventory record already states -- its role, and its
	// cluster if it has one. Sorted and de-duplicated by the renderer.
	//
	// ⚠️ A GROUP IS FOR group_vars AND NOTHING ELSE; A PLAY SHOULD STILL
	// SAY `hosts: all`. truss already limits every run to exactly the
	// hosts whose config names that play, so a play that narrows itself
	// again by group is applying the same filter twice from two sources --
	// and the day a host's role is edited, the play silently stops
	// matching it while truss goes on reporting the host as one it
	// configures. The group exists so group_vars/<role>/ resolves, which
	// is the thing ansible cannot do from --limit.
	Groups []string
}

// renderInventory writes targets as an ansible YAML inventory.
//
// ⚠️ HAND-WRITTEN YAML, AND DELIBERATELY SO. The only values that reach it
// are a host name, an address and a login, every one of which is already
// constrained by inventory.checkHost before a record is accepted -- so a
// YAML library would be a dependency bought to escape values that cannot
// contain anything needing escaping. What this function must do instead is
// REFUSE anything that slipped through, which it does below, because a
// renderer that quietly emits a broken file is the failure a marshaller
// would not save us from either.
func renderInventory(targets []Target) ([]byte, error) {
	if len(targets) == 0 {
		return nil, fmt.Errorf("ansible: refuses to render an inventory with no targets")
	}
	sorted := make([]Target, len(targets))
	copy(sorted, targets)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by truss for one play. Do not edit; it is rebuilt every run.\n")
	b.WriteString("all:\n  hosts:\n")
	seen := map[string]bool{}
	for _, t := range sorted {
		if err := checkToken("name", t.Name); err != nil {
			return nil, err
		}
		if seen[t.Name] {
			return nil, fmt.Errorf("ansible: %q appears twice in one inventory", t.Name)
		}
		seen[t.Name] = true

		fmt.Fprintf(&b, "    %s:\n", t.Name)
		host, port, err := splitAddress(t.Address)
		if err != nil {
			return nil, fmt.Errorf("ansible: %s: %w", t.Name, err)
		}
		if host != "" {
			if err := checkToken("address", host); err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "      ansible_host: %q\n", host)
		}
		if port != "" {
			fmt.Fprintf(&b, "      ansible_port: %s\n", port)
		}
		if t.User != "" {
			if err := checkToken("user", t.User); err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "      ansible_user: %q\n", t.User)
		}
	}

	// Groups come after every host, as `children` of all, because ansible
	// resolves a child group's membership against hosts it already knows.
	groups := map[string][]string{}
	for _, t := range sorted {
		for _, g := range t.Groups {
			if err := checkToken("group", g); err != nil {
				return nil, err
			}
			if !contains(groups[g], t.Name) {
				groups[g] = append(groups[g], t.Name)
			}
		}
	}
	if len(groups) > 0 {
		names := make([]string, 0, len(groups))
		for g := range groups {
			names = append(names, g)
		}
		sort.Strings(names)
		b.WriteString("  children:\n")
		for _, g := range names {
			fmt.Fprintf(&b, "    %s:\n      hosts:\n", g)
			for _, h := range groups[g] {
				fmt.Fprintf(&b, "        %s:\n", h)
			}
		}
	}
	return []byte(b.String()), nil
}

func contains(ss []string, v string) bool {
	for _, s := range ss {
		if s == v {
			return true
		}
	}
	return false
}

// checkToken refuses a value that would not survive being written into the
// generated file as itself. inventory.checkHost already refuses these at
// the record, so reaching this is a programming error upstream rather than
// a bad record -- which is exactly why it returns an error instead of
// escaping: silently repairing a value here would hide the upstream hole.
func checkToken(field, v string) error {
	if v == "" {
		return fmt.Errorf("ansible: empty %s in an inventory target", field)
	}
	if strings.ContainsAny(v, " \t\r\n\"'#:") {
		return fmt.Errorf("ansible: %s %q cannot be written to an inventory: it carries whitespace, a quote, %q or %q", field, v, "#", ":")
	}
	return nil
}

// splitAddress separates "<host>" from "<host>:<port>", and returns an
// empty host for an empty address -- see Target.Address.
//
// ⚠️ A BARE IPv6 LITERAL IS A HOST, NOT A MALFORMED HOST:PORT.
// net.SplitHostPort("::1") fails with "too many colons", which is the
// correct answer to the question it was asked and the wrong answer to
// ours. A bracketed literal is the only way IPv6 can carry a port, so an
// unbracketed one that fails to split is simply an address with no port.
func splitAddress(addr string) (host, port string, err error) {
	if addr == "" {
		return "", "", nil
	}
	if h, p, e := net.SplitHostPort(addr); e == nil {
		if p == "" {
			return "", "", fmt.Errorf("address %q has a colon but no port", addr)
		}
		for _, r := range p {
			if r < '0' || r > '9' {
				return "", "", fmt.Errorf("address %q has a non-numeric port %q", addr, p)
			}
		}
		return h, p, nil
	}
	return strings.Trim(addr, "[]"), "", nil
}
